### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, chmod '$ATOM_HOME/packages/wakatime/lib/wakati...

### ISSUE THREAD

**Issue by martinskruze** [wakatime/atom-wakatime#100]
[Enter steps to reproduce:]

1. it happens whilst opening atom

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.3
**Thrown From**: [wakatime](https://github.com/wakatime/atom-wakatime) package 9.0.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, chmod '/Users/username/.atom/packages/wakatime/lib/wakatime-cli/wakatime-cli'

```
At fs.js:115

Error: ENOENT: no such file or directory, chmod '/Users/username/.atom/packages/wakatime/lib/wakatime-cli/wakatime-cli'
    at Object.chmodSync (fs.js:1001:3)
    at /packages/wakatime/lib/wakatime.coffee:321:12
    at /packages/wakatime/lib/wakatime.coffee:361:11
    at FSReqWrap.oncomplete (fs.js:141:20)
```

### Commands

```
```

### Non-Core Packages

```
afterglow-monokai-syntax 1.3.7 
afterglow-plus 3.0.0 
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-inline-blame 0.0.7 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
dash 1.7.1 
file-icons 2.1.39 
firewatch-syntax 1.1.1 
fonts 3.10.0 
goto-definition 1.3.4 
language-docker 1.1.8 
language-haml 0.32.1 
language-rspec 0.12.1 
language-scala 1.1.10 
linter-spell-ruby 0.4.0 
native-ui 0.27.0 
nord-atom-syntax 0.10.0 
nord-atom-ui 0.12.0 
northem-dark-atom-ui 2.1.0 
pain-split 1.4.0 
pristine-ui 1.1.11 
ruby-solargraph 0.6.1 
sort-lines 0.19.0 
split-diff 1.6.1 
sync-settings 4.0.0 
TabNine 2.1.7 
toggle-quotes 1.1.4 
touchbar 0.14.2 
wakatime 9.0.2 
```

**Comment by martinskruze** [comment]
reinstallilng helped
