### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'statusCode' in undefined

### ISSUE THREAD

**Issue by davidsmandrade** [wakatime/atom-wakatime#119]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Ubuntu 20.04.3
**Thrown From**: [wakatime](https://github.com/wakatime/atom-wakatime) package 11.0.6

### Stack Trace

Uncaught TypeError: Cannot use 'in' operator to search for 'statusCode' in undefined

```
At /home/davidandrade/.atom/packages/wakatime/lib/wakatime.js:350

TypeError: Cannot use 'in' operator to search for 'statusCode' in undefined
    at Request._callback (/packages/wakatime/lib/wakatime.js:350:61)
    at self.callback (/packages/atom-updater-linux/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.onRequestError (/packages/atom-updater-linux/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:223:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

### Commands

```
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-clock 0.1.18 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-shortcuts 0.0.2 
atom-updater-linux 1.3.0 
autocomplete-python 1.17.0 
busy-signal 2.0.1 
file-icons 2.1.47 
highlight-selected 0.17.0 
Hydrogen 2.16.3 
intentions 2.1.1 
linter 3.4.0 
linter-ui-default 3.4.1 
minimap 4.40.0 
platformio-ide-terminal 2.10.1 
python-indent 1.2.6 
python-isort 0.0.7 
script 3.32.2 
seti-ui 1.11.0 
teletype 0.13.4 
wakatime 11.0.6 
```

**Comment by alanhamlett** [comment]
Fixed in v11.0.7.
