### ISSUE TITLE
Keeps failing

### ISSUE THREAD

**Issue by captjay98** [wakatime/atom-wakatime#120]
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! Unexpected end of JSON input while parsing near '...=N1Mv\r\n-----END PGP'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jamal Ibrahim Umar\.atom\.apm\_logs\2022-01-30T14_11_00_891Z-debug.log

**Comment by alanhamlett** [comment]
How about with the latest release?

**Comment by captjay98** [comment]
I'm still getting the same error![Uploading v2{2ec83a1} (f5c7dfa3-bf84-4cc4-bbac-27c51df14a38 id=0x7f0a03a2 tag=BaseCommentFragment) …]()

**Comment by captjay98** [comment]
I'm still getting the same error![Uploading v2{2ec83a1} (f5c7dfa3-bf84-4cc4-bbac-27c51df14a38 id=0x7f0a03a2 tag=BaseCommentFragment) …]()

**Comment by alanhamlett** [comment]
Might be a problem with Atom, because it lazy-installs dependencies when installing plugins. Try deleting this folder:
`C:\Users\Jamal Ibrahim Umar\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\`
Then re-install the atom-wakatime plugin. Does that fix it?

**Comment by captjay98** [comment]
Installing “wakatime@11.0.9” failed.[Hide output…]()
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'underscore-plus'
Require stack:
- C:\Users\Jamal Ibrahim Umar\AppData\Local\atom\app-1.58.0\resources\app\apm\lib\apm-cli.js
- C:\Users\Jamal Ibrahim Umar\AppData\Local\atom\app-1.58.0\resources\app\apm\lib\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)

    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Jamal Ibrahim Umar\AppData\Local\atom\app-1.58.0\resources\app\apm\lib\apm-cli.js:9:7)
    at Object.<anonymous> (C:\Users\Jamal Ibrahim Umar\AppData\Local\atom\app-1.58.0\resources\app\apm\lib\apm-cli.js:251:4)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)

    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [

    'C:\\Users\\Jamal Ibrahim Umar\\AppData\\Local\\atom\\app-1.58.0\\resources\\app\\apm\\lib\\apm-cli.js',
    'C:\\Users\\Jamal Ibrahim Umar\\AppData\\Local\\atom\\app-1.58.0\\resources\\app\\apm\\lib\\cli.js'
  ]
}

**Comment by alanhamlett** [comment]
That still looks like an Atom issue. Try deleting `C:\Users\Jamal Ibrahim Umar\AppData\Local\atom`, re-installing Atom, then re-installing atom-wakatime?

**Comment by gandarez** [comment]
Was that solved @captjay98?

**Comment by alanhamlett** [comment]
Closing as fixed due to no response.
