### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, chmod 'C:\Users\Edvin\.atom\packages\wakatime\lib...

### ISSUE THREAD

**Issue by hultberg** [wakatime/atom-wakatime#20]
Was just using atom as normal and after going in the menues this error occurred.

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [wakatime](https://github.com/wakatime/atom-wakatime) package, v4.0.11

### Stack Trace

Uncaught Error: EPERM: operation not permitted, chmod 'C:\Users\Edvin\.atom\packages\wakatime\lib\wakatime-master\.gitignore'

```
At fs.js:1004

Error: EPERM: operation not permitted, chmod 'C:\Users\Edvin\.atom\packages\wakatime\lib\wakatime-master\.gitignore'
  at Error (native)
  at Object.fs.chmodSync (fs.js:1004:18)
  at Object.module.exports.writeFileTo (C:\Users\Edvin\.atom\packages\wakatime\node_modules\adm-zip\util\utils.js:108:20)
  at C:\Users\Edvin\.atom\packages\wakatime\node_modules\adm-zip\adm-zip.js:361:23
  at Array.forEach (native)
  at Object.extractAllTo (C:\Users\Edvin\.atom\packages\wakatime\node_modules\adm-zip\adm-zip.js:352:26)
  at unzip (C:\Users\Edvin\.atom\packages\wakatime\lib\wakatime.coffee:229:13)
  at C:\Users\Edvin\.atom\packages\wakatime\lib\wakatime.coffee:204:13
  at next (C:\Users\Edvin\.atom\packages\wakatime\node_modules\rimraf\rimraf.js:72:7)
  at CB (C:\Users\Edvin\.atom\packages\wakatime\node_modules\rimraf\rimraf.js:108:9)
  at C:\Users\Edvin\.atom\packages\wakatime\node_modules\rimraf\rimraf.js:244:18
  at next (C:\Users\Edvin\.atom\packages\wakatime\node_modules\rimraf\rimraf.js:72:7)
  at CB (C:\Users\Edvin\.atom\packages\wakatime\node_modules\rimraf\rimraf.js:108:9)
  at C:\Users\Edvin\.atom\packages\wakatime\node_modules\rimraf\rimraf.js:164:7
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -0:11.9.0 project-manager:save-project (div.settings-view.pane-item)
     -0:10.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:10.7.0 focus (atom-workspace.workspace.scrollbars-visible-always.theme-base16-ocean-dark-syntax-theme.theme-one-dark-ui)
     -0:03.9.0 project-manager:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-base16-ocean-dark-syntax-theme.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-ocean-dark-syntax-theme"
    ],
    "disabledPackages": [
      "silent-sync",
      "php-class-tree"
    ],
    "projectHome": "C:\\Users\\Edvin\\coretrek\\frontend"
  },
  "wakatime": {
    "ignore": [
      "^/var/",
      "^/tmp/",
      "^/private/",
      "COMMIT_EDITMSG$",
      "PULLREQ_EDITMSG$",
      "MERGE_MSG$"
    ],
    "apikey": "74501759-c5ed-46f4-b597-270dc9e4eb19"
  }
}
```

### Installed Packages

```coffee
# User
base16-ocean-dark-syntax-theme, v0.1.5
color-picker, v2.0.7
docblockr, v0.7.2
editorconfig, v1.0.1
file-icons, v1.5.8
minimap, v4.10.1
project-manager, v1.15.10
remote-sync, v3.1.2
wakatime, v4.0.11

# Dev
No dev packages
```

**Comment by inderjits** [comment]
Same Error. Please try to resolve soon.
