### ISSUE TITLE
Cannot find module 'extend' (Failed to load the wakatime package)

### ISSUE THREAD

**Issue by Gurpartap** [wakatime/atom-wakatime#27]
Occurred after launching a new atom window from the command line after updating to latest wakatime (didn't restart atom, if it matters).

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [wakatime](https://github.com/wakatime/atom-wakatime) package, v4.0.17

### Stack Trace

Failed to load the wakatime package

```
At Cannot find module 'extend'

Error: Cannot find module 'extend'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/Gurpartap/.atom/packages/wakatime/node_modules/request/index.js:17:29)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/Gurpartap/.atom/packages/wakatime/lib/wakatime.coffee:14:11)
    at Object.<anonymous> (/Users/Gurpartap/.atom/packages/wakatime/lib/wakatime.coffee:1:1)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:759:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:190:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:405:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:369:14)
    at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:667:21)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:82:25)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:35:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "sepia-syntax"
    ]
  },
  "wakatime": {
    "ignore": [
      "^/var/",
      "^/tmp/",
      "^/private/",
      "COMMIT_EDITMSG$",
      "PULLREQ_EDITMSG$",
      "MERGE_MSG$"
    ],
    "apikey": "---"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.8.7
build, v0.46.0
clang-format, v1.16.0
formatter-clang-format, v0.1.1
go-plus, v3.5.1
highlight-selected, v0.10.1
language-swift, v0.4.0
linter, v1.5.1
linter-clang, v3.2.1
pretty-json, v0.4.1
project-manager, v2.5.1
sepia-syntax, v1.0.5
terminal-panel, v1.14.1
wakatime, v4.0.17

# Dev
No dev packages
```

**Comment by alanhamlett** [comment]
Does this happen every time you launch Atom from command line, or just that one time after upgrading?

**Comment by Gurpartap** [comment]
It's still happening. Even with blank document. And it doesn't matter which way I launch it.

**Comment by Gurpartap** [comment]
<img width="717" alt="screen shot 2015-09-13 at 4 47 31 am" src="https://cloud.githubusercontent.com/assets/39792/9834320/ad26ee8e-59d2-11e5-81cd-ae679f562008.png">

**Comment by alanhamlett** [comment]
Can you try reinstalling the wakatime plugin? I'm not seeing the error come from any atom-wakatime code file, so I don't know how to begin fixing this.

**Comment by Gurpartap** [comment]
Not getting the error anymore after reinstalling the wakatime package. While it does sound like atom's package handling might have failed here, it only happened with the wakatime package. Hmm

Feel free to close if you're certain this wasn't caused by wakatime package though.

**Comment by alanhamlett** [comment]
Maybe it was a corrupted download with the wakatime package or one of it's dependencies... I'll close this issue now.

**Comment by kidchenko** [comment]
+1

**Comment by kidchenko** [comment]
Failed to load the wakatime package

```
Cannot find module 'adm-zip'
Hide Stack Trace
Error: Cannot find module 'adm-zip'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\JoséBarbosa\AppData\Local\atom\app-1.1.0\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\JoséBarbosa\.atom\packages\wakatime\lib\wakatime.coffee:9:10)
  at Object.<anonymous> (C:\Users\JoséBarbosa\.atom\packages\wakatime\lib\wakatime.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\JoséBarbosa\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\JoséBarbosa\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:725:34)
  at C:\Users\JoséBarbosa\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:176:28
  at Package.module.exports.Package.measure (C:\Users\JoséBarbosa\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:153:15)
  at Package.module.exports.Package.load (C:\Users\JoséBarbosa\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:167:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\JoséBarbosa\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:396:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\JoséBarbosa\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:473:30)
  at C:\Users\JoséBarbosa\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:444:29
  at exit (C:\Users\JoséBarbosa\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
  at triggerExitCallback (C:\Users\JoséBarbosa\AppData\Local\atom\app-1.1.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\JoséBarbosa\AppData\Local\atom\app-1.1.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by alanhamlett** [comment]
@kidchenko did you try re-installing the plugin? Looks like one of the dependencies wasn't installed correctly.
