### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addListener' of undefined

### ISSUE THREAD

**Issue by joliveros** [wakatime/atom-wakatime#28]
[Enter steps to reproduce below:]

1. typing in current document or saving and I get this error.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [wakatime](https://github.com/wakatime/atom-wakatime) package, v4.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'addListener' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:809

TypeError: Cannot read property 'addListener' of undefined
  at Object.exports.execFile (child_process.js:245:15)
  at Object.module.(anonymous function) [as execFile] (ATOM_SHELL_ASAR.js:163:20)
  at /Users/chino/.atom/packages/wakatime/lib/wakatime.coffee:292:17
  at pythonLocation (/Users/chino/.atom/packages/wakatime/lib/wakatime.coffee:116:5)
  at sendHeartbeat (/Users/chino/.atom/packages/wakatime/lib/wakatime.coffee:280:5)
  at /Users/chino/.atom/packages/wakatime/lib/wakatime.coffee:93:11
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1004:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:584:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:547:18)
  at Pane.module.exports.Pane.saveItems (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:585:14)
  at PaneContainer.module.exports.PaneContainer.saveAll (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:217:14)
  at Workspace.module.exports.Workspace.saveAll (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:601:33)
  at atom-workspace.atom.commands.add.window:save-all (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:275:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -1:31.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -1:29.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:28.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:28.1.0 core:move-up (atom-text-editor.editor.is-focused)
  7x -1:27.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:26.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:26 core:select-up (atom-text-editor.editor.is-focused)
     -1:25.6.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -1:25.4.0 window:save-all (atom-text-editor.editor.is-focused)
     -1:12.4.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:12.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:12.1.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:11.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:11.8.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:11.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  5x -1:10.7.0 window:save-all (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "atom-light-ui",
      "one-light-syntax"
    ]
  },
  "wakatime": {
    "apikey": "b60c18db-a462-4c0f-a16e-f0a55bf76d19"
  }
}
```

### Installed Packages

```coffee
# User
docblockr, v0.7.3
language-swift, v0.4.0
pretty-json, v0.4.1
react, v0.12.9
react-snippets, v0.2.0
tidy-tabs, v0.2.0
wakatime, v4.1.0

# Dev
No dev packages
```

**Comment by alanhamlett** [comment]
@joliveros you should change your api key at https://wakatime.com/settings, since it's now publicly displayed in this issue.

I've released a new version 4.1.1. Can you try updating to this new release and check if it's working?
