### ISSUE TITLE
Uncaught Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by rafaellott** [wakatime/atom-wakatime#47]
1. Open Atom normally by command line "atom ."
2. When it opens occurs the error and when I try to edit the file

PS.: I believe it is related to folder permission or something, cause I opened atom as root and the error didn't occur.

**Atom Version**: 1.7.2
**System**: elementary OS
**Thrown From**: [wakatime](https://github.com/wakatime/atom-wakatime) package, v5.0.8
### Stack Trace

Uncaught Error: spawn ENOTDIR

```
At internal/child_process.js:298

Error: spawn ENOTDIR
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:374:9)
    at exports.execFile (child_process.js:163:15)
    at module.(anonymous function) (ATOM_SHELL_ASAR.js:185:20)
    at pythonLocation (/home/rafaellott/.atom/packages/wakatime/lib/wakatime.coffee:182:5)
    at /home/rafaellott/.atom/packages/wakatime/lib/wakatime.coffee:188:9
    at exithandler (child_process.js:232:5)
    at ChildProcess.errorhandler (child_process.js:244:5)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```
### Commands

```
     -6:11.4.0 window:toggle-dev-tools (atom-pane.pane.active)
     -0:37.2.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -0:36.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:35.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:21.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:21.4.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:16.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:15.7.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autocomplete-html-entities"
    ],
    "projectHome": "/data/www/"
  },
  "wakatime": {
    "apikey": "xxxxxxxxxxxxx"
  }
}
```
### Installed Packages

``` coffee
# User
autoclose-html, v0.23.0
autocomplete-python, v1.7.2
editorconfig, v1.4.0
highlight-selected, v0.11.2
linter, v1.11.4
linter-pep8, v1.2.1
minimap, v4.23.1
minimap-bookmarks, v0.3.0
minimap-cursorline, v0.1.0
minimap-git-diff, v4.3.0
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.0
python-indent, v0.4.3
python-tools, v0.6.7
svn, v0.0.9
tabs-to-spaces, v1.0.2
wakatime, v5.0.8

# Dev
No dev packages
```

**Comment by theotheo** [comment]
Same issue, guys. Is there a workaround for it?

**Comment by designviacode** [comment]
same issue here as well.. !

**Comment by alanhamlett** [comment]
@theotheo and @designviacode which OS are you using?

**Comment by designviacode** [comment]
@alanhamlett Ubuntu 16.04, 64-bit.

**Comment by GFite** [comment]
[Enter steps to reproduce:]

1. open atom
2. observe red error box

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [wakatime](https://github.com/wakatime/atom-wakatime) package 6.0.13


### Stack Trace

Uncaught Error: spawn ENOTDIR

```
At internal/child_process.js:313

Error: spawn ENOTDIR
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:392:9)
    at exports.execFile (child_process.js:155:15)
    at module.(anonymous function) (ELECTRON_ASAR.js:195:20)
    at pythonLocation (/packages/wakatime/lib/wakatime.coffee:252:5)
    at /packages/wakatime/lib/wakatime.coffee:259:9
    at exithandler (child_process.js:225:5)
    at ChildProcess.errorhandler (child_process.js:237:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
wakatime 6.0.13 
zentabs 0.8.8 
```

**Comment by GFite** [comment]
The above error occurred after setting the config in the atom app itself. I was able to resolve this by installing wakatime using apm on Ubuntu 16.04

    apm install wakatime

**Comment by alanhamlett** [comment]
> after setting the config in the atom app itself

Which config?

**Comment by GFite** [comment]
@alanhamlett the config I am referring to is in the UI: Atom-->Packages-->Settings View-->Manage Packages-->wakatime settings

I simply installed using apm from the cli without altering what I had done in the UI and it now works properly.

**Comment by alanhamlett** [comment]
It's probably related to npm dependencies not correctly installing when Atom installs the wakatime plugin, since reinstalling the plugin would also reinstall the npm dependencies.

**Comment by FabienDeborde** [comment]
I am having the same issue for the past 2 weeks. 
I tried to delete all wakatime files, reinstall using the cli and also directly using Atom package installer. 
I tried using sudo with apm install command but nothing seems to be working.
Is there another way to install it without using the apm command?

**Atom**: 1.15.0 x64 <br/>
**OS**: Linux Mint 18 <br/>
**Thrown From**: wakatime package 7.0.2

##Stack Trace

```
Uncaught Error: spawn ENOTDIR
internal/child_process.js:313
Hide Stack Trace
Error: spawn ENOTDIR
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:392:9)
    at Object.exports.execFile (child_process.js:155:15)
    at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:195:20)
    at pythonLocation (/.atom/packages/wakatime/lib/wakatime.coffee:294:19)
    at /.atom/packages/wakatime/lib/wakatime.coffee:301:9
    at exithandler (child_process.js:225:5)
    at ChildProcess.errorhandler (child_process.js:237:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by FabienDeborde** [comment]
I have no idea what changed but today it is working again.

**Comment by nicinabox** [comment]
I've also been having this error lately. I tracked it back some strangeness with python2/python3 and homebrew. Having brew's `python3` in the PATH seemed to fix it for me.
