### ISSUE TITLE
Error when using atom-term2

### ISSUE THREAD

**Issue by hughsk** [wakatime/atom-wakatime#5]
Happened when closing a tab created by [atom-term2](https://github.com/webBoxio/atom-term2), though I wasn't able to reproduce the error a second time. Hope this helps – thanks!

![screenshot_2015-01-06_10 17 01 pm](https://cloud.githubusercontent.com/assets/569817/5636392/f6588e64-95f1-11e4-843c-a62ff8b70137.png)

```
TypeError: undefined is not a function
  at /Users/hughsk/.atom/packages/wakatime/lib/wakatime.coffee:36:31
  at TextBuffer.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:591:12)
  at BufferPatch.module.exports.BufferPatch.applyTo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/buffer-patch.js:74:21)
  at Transaction.module.exports.Transaction.applyTo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/transaction.js:60:29)
  at History.module.exports.History.abortTransaction (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:162:24)
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:119:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:683:27)
  at TextBuffer.module.exports.TextBuffer.setTextViaDiff (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:452:19)
  at TextBuffer.module.exports.TextBuffer.reload (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:979:12)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1100:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/event-kit/lib/emitter.js:35:25)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:337:38
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:749:13)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:557:44
  at flush (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:378:11)
```

**Comment by hughsk** [comment]
Correction: this happens any time after I run `npm install` from `atom-term2`.

**Comment by alanhamlett** [comment]
I'm closing this issue since it should be fixed now.
