### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by edobry** [wakatime/atom-wakatime#50]
1. Launch Atom

**Atom Version**: 1.7.3
**System**: Linux Mint
**Thrown From**: [wakatime](https://github.com/wakatime/atom-wakatime) package, v5.0.8
### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:298

Error: spawn EACCES
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:374:9)
    at exports.execFile (child_process.js:163:15)
    at module.(anonymous function) (ATOM_SHELL_ASAR.js:185:20)
    at module.(anonymous function) (ATOM_SHELL_ASAR.js:185:20)
    at pythonLocation (/home/eugene/.atom/packages/wakatime/lib/wakatime.coffee:182:5)
    at /home/eugene/.atom/packages/wakatime/lib/wakatime.coffee:188:9
    at exithandler (child_process.js:232:5)
    at ChildProcess.errorhandler (child_process.js:244:5)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:465:9)
    at process._tickDomainCallback (node.js:420:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "wrap-guide",
      "npm-docs",
      "node-resolver"
    ],
    "packagesWithKeymapsDisabled": [
      "tool-bar-almighty",
      "tool-bar"
    ],
    "projectHome": "/home/eugene/Projects",
    "themes": [
      "seti-ui",
      "grandson-of-obsidian"
    ]
  },
  "wakatime": {
    "apikey": "2e29638f-ffb2-4f12-b728-4aab075f63a0"
  }
}
```
### Installed Packages

``` coffee
# User
autoclose-html, v0.23.0
emmet, v2.4.3
git-log, v0.4.1
grandson-of-obsidian, v0.1.0
highlight-selected, v0.11.2
js-refactor, v0.6.0
language-groovy, v0.6.0
linter, v1.11.4
linter-eslint, v7.2.2
merge-conflicts, v1.4.2
minimap, v4.23.5
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.1
minimap-selection, v4.4.0
multi-wrap-guide, v0.23.5
node-debugger, v1.5.1
pigments, v0.26.2
pretty-json, v1.0.3
project-manager, v2.9.7
refactor, v0.6.0
rest-client, v1.1.0
seti-ui, v1.1.2
terminal-plus, v0.14.5
tool-bar, v0.4.0
tool-bar-almighty, v0.6.1
tree-view-git-status, v0.2.3
wakatime, v5.0.8

# Dev
No dev packages
```

**Comment by alanhamlett** [comment]
@edobry please generate a new api key here: https://wakatime.com/settings because your api key is in the config posted above. Sorry about this, hopefully we can prevent it with #26 in the future.

**Comment by alanhamlett** [comment]
Closing as stale.
