### ISSUE TITLE
Failed to activate the wakatime package

### ISSUE THREAD

**Issue by perseghini** [wakatime/atom-wakatime#63]
[Enter steps to reproduce below:]

1. Open Atom

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [wakatime](https://github.com/wakatime/atom-wakatime) package, v6.0.9

### Stack Trace

Failed to activate the wakatime package

```
At Cannot find module 'extend'

Error: Cannot find module 'extend'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/perseghini/.atom/packages/wakatime/node_modules/request/index.js:17:29)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/perseghini/.atom/packages/wakatime/lib/wakatime.coffee:23:11)
    at Object.<anonymous> (/Users/perseghini/.atom/packages/wakatime/lib/wakatime.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "git-log"
    ],
    "themes": [
      "atom-material-ui",
      "solarized-light-syntax"
    ]
  },
  "wakatime": {
    "apikey": "Saved in your ~/.wakatime.cfg file",
    "ignore": [
      "^/var/",
      "^/tmp/",
      "^/private/",
      "COMMIT_EDITMSG$",
      "PULLREQ_EDITMSG$",
      "MERGE_MSG$"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-material-ui, v1.2.13
autocomplete-python, v1.8.1
color-picker, v2.1.1
file-icons, v1.7.15
highlight-selected, v0.11.2
last-cursor-position, v0.9.0
linter, v1.11.10
linter-flake8, v1.13.2
merge-conflicts, v1.4.4
pigments, v0.29.2
wakatime, v6.0.9
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by alanhamlett** [comment]
Can you reinstall the plugin and see if that fixes the issue?

**Comment by perseghini** [comment]
Yes, it seems to work now after reinstalling it !
Thanks
