### ISSUE TITLE
Uncaught Error: tunneling socket could not be established

### ISSUE THREAD

**Issue by geminorum** [wakatime/atom-wakatime#72]
**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [wakatime](https://github.com/wakatime/atom-wakatime) package 7.0.0

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8080

```
At stream.js:74

Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8080
    at ClientRequest.onError (/packages/wakatime/node_modules/tunnel-agent/index.js:177:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -3:38.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-light-ui)
     -3:32.3.0 project-manager:list-projects (atom-pane.pane.active)
     -3:30.9.0 editor:consolidate-selections (input.hidden-input)
     -3:30.9.0 atom-minify:close-panel (input.hidden-input)
     -3:30.9.0 core:cancel (input.hidden-input)
     -3:27.6.0 project-manager:list-projects (atom-pane.pane.active)
     -3:24.3.0 editor:consolidate-selections (input.hidden-input)
     -3:24.3.0 atom-minify:close-panel (input.hidden-input)
     -3:24.3.0 core:cancel (input.hidden-input)
     -3:18.4.0 flex-tool-bar:edit-config-file (atom-pane.pane.active)
     -3:13.9.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-light-ui)
     -1:16.1.0 core:select-all (input.hidden-input)
     -1:15.7.0 core:delete (input.hidden-input)
     -1:02.5.0 core:paste (input.hidden-input)
```

**Comment by alanhamlett** [comment]
How often does this error occur?

**Comment by geminorum** [comment]
every time I open a new atom window.

also status bar is freezing on "downloading wakatime-cli..."

**Comment by geminorum** [comment]
no longer an issue in 7.0.2
