### ISSUE TITLE
Uncaught Error: Cannot find module 'adm-zip'

### ISSUE THREAD

**Issue by GuoxiW** [wakatime/atom-wakatime#81]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [wakatime](https://github.com/wakatime/atom-wakatime) package 7.0.4

### Stack Trace

Uncaught Error: Cannot find module 'adm-zip'

```
At C:\Users\Guoxi-work\AppData\Local\atom\app-1.23.3\resources\app\static\<embedded>:1

Error: Cannot find module 'adm-zip'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.23.3/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.23.3/resources/app/src/native-compile-cache.js:66:33)
    at loadDependencies (/packages/wakatime/lib/wakatime.coffee:302:14)
    at delayedActivate (/packages/wakatime/lib/wakatime.coffee:58:7)
```

### Commands

```
```

### Non-Core Packages

```
wakatime 7.0.4 
```

**Comment by alanhamlett** [comment]
Sometimes the plugin's dependencies fail to install, but re-installing the WakaTime plugin should fix it.
