### ISSUE TITLE
Uncaught Error: spawn EBUSY

### ISSUE THREAD

**Issue by yasirabd** [wakatime/atom-wakatime#85]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [wakatime](https://github.com/wakatime/atom-wakatime) package 7.0.5

### Stack Trace

Uncaught Error: spawn EBUSY

```
At internal/child_process.js:323

Error: spawn EBUSY
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:514:9)
    at Object.exports.execFile (child_process.js:224:15)
    at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:200:20)
    at /packages/wakatime/lib/wakatime.coffee:490:28
    at pythonLocation (/packages/wakatime/lib/wakatime.coffee:276:5)
    at sendHeartbeat (/packages/wakatime/lib/wakatime.coffee:463:5)
    at /packages/wakatime/lib/wakatime.coffee:265:11
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at TextEditor.cursorMoved (~/AppData/Local/atom/app-1.31.1/resources/app/src/text-editor.js:2887:31)
    at Selection.markerDidChange (~/AppData/Local/atom/app-1.31.1/resources/app/src/selection.js:1037:25)
    at Selection.marker.onDidChange.e (~/AppData/Local/atom/app-1.31.1/resources/app/src/selection.js:21:45)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/text-buffer/lib/display-marker.js:248:33)
    at ~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/text-buffer/lib/display-marker.js:53:32
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Marker.module.exports.Marker.emitChangeEvent (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/text-buffer/lib/marker.js:441:26)
    at Marker.module.exports.Marker.update (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/text-buffer/lib/marker.js:374:18)
    at MarkerLayer.module.exports.MarkerLayer.restoreFromSnapshot (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/text-buffer/lib/marker-layer.js:303:24)
    at TextBuffer.module.exports.TextBuffer.restoreFromMarkerSnapshot (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1749:87)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1032:20)
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:978:20)
    at TextEditor.transact (~/AppData/Local/atom/app-1.31.1/resources/app/src/text-editor.js:2007:30)
    at TextEditor.moveCursors (~/AppData/Local/atom/app-1.31.1/resources/app/src/text-editor.js:2880:23)
    at TextEditor.setCursorScreenPosition (~/AppData/Local/atom/app-1.31.1/resources/app/src/text-editor.js:2691:23)
    at TextEditorComponent.didMouseDownOnContent (~/AppData/Local/atom/app-1.31.1/resources/app/src/text-editor-component.js:1808:25)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-python 1.10.12 
react 0.18.0 
react-snippets 1.1.1 
wakatime 7.0.5 
```

**Comment by alanhamlett** [comment]
Thanks for the report. Can you provide more info about this issue? Does it happen often, or has it only happened once?

**Comment by alanhamlett** [comment]
If it's intermittent, the version 7.0.6 released today will retry executing this command 5 times before raising an error.

Let me know if it's happening often even after upgrading to 7.0.6 and we can reopen this issue.
